resolver: lts-9.21

packages:
- ./hello-world
- ./hello-postgresql

docker:
  enable: true
  image: "builder:latest"

image:
  containers:
    - base: runner:latest
      name: hello-world-exe
      executables:
        - hello-world-exe
    - base: runner-libpq:latest
      name: hello-postgresql-exe
      executables:
        - hello-postgresql-exe
