name:                hello-postgresql
version:             0.1.0.0
github:              "naushadh/hello-world"
license:             BSD3
author:              "Naushadh"
maintainer:          "naushadh@protonmail.com"
copyright:           "2018 Naushadh"

extra-source-files:
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/naushadh/hello-world#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple

library:
  source-dirs: src

executables:
  hello-postgresql-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-postgresql

tests:
  hello-postgresql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-postgresql
