resolver: lts-12.14

packages:
- .

# the following flags are meant for use with Dockerfile
compiler: ghc-8.4.3 # this MUST match the resolver's GHC; ensures GHC isn't redownloaded.
allow-different-user: true
system-ghc: true # don't bother building GHC as it is error prone on Alpine; we assume system has the right compiler
